
customDataPath: false
# customDataPath: /var/lib/webca

ldapAuth:
  url: "ldaps://192.168.10.20:636"
  domain: 'app-scape.lab'

folders:
  - root
  - req
  - crt
  - key

endings:
  cert: ".crt"
  req: ".csr"
  key: ".key"

subjects: 
  commonname: "CN"
  country: "C"
  state: "ST"
  city: "L"
  organization: "O"
  unit: "OU"
  email: "emailAddress"

sanTypes: 
  - IP
  - DNS

mandaSubjects: 
  - commonname
  - country
  - organization
  - email

stdRootValidity: 315360000 # 10*365*24*60*60
stdCertValidity: 94608000 # 3*365*24*60*60
keyLen: 2048

